[package]
name = "sfml"
description = "Rust binding for sfml"
version = "0.10.0"
authors = [
	"Jeremy Letang <letang.jeremy@gmail.com>",
	"Tad Hardesty <tad@platymuus.com>"
]

documentation = "http://www.rust-sfml.org/doc/rsfml/index.html"
homepage = "http://www.rust-sfml.org/"
repository = "https://github.com/jeremyletang/rust-sfml"
license = "zlib-acknowledgement"

[dependencies]
libc = ">=0.1.5"
bitflags = ">=0.1"

[dev-dependencies]
rand = ">=0.3.0"

[lib]
name = "sfml"
crate-type = ["dylib", "rlib"]
